# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#features"
  weight = 1

[[main]]
  name = "Features"
  url = "#features"
  weight = 2

[[main]]
  name = "Benchmarks"
  url = "#benchmarks"
  weight = 3

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 4

[[main]]
  name = "Resources"
  url = "#resources"
  weight = 5


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
